### ISSUE TITLE
Recipe for enabling Jupyter notebooks inside SMuRF docker?

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#111]
Not urgent, but whenever you get a chance @jlashner could you please paste how you've been enabling Jupyter in the pysmurf dockers?

**Comment by jlashner** [comment]
Submitted a [PR](https://github.com/slaclab/pysmurf-docker/pull/3) to pysmurf-docker to enable jupyter in pysmurf containers. Before I was building a custom image to do it.

Here's an example docker-compose service that will start a jupyter notebook, with password and port specified as environment variables. By default, the password is "password" and the port is 8888.
```
    jupyter:
        image: pysmurf
        ports:
            - 8888:8888
        environment:
            JUPYTER_PW: abcd
            JUPYTER_PORT: 8888
        entrypoint: jupyter notebook
```
