### ISSUE TITLE
Switching pysmurf-server off of network mode host

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#297]
I'm trying to switch the smurf-streamer off of network-mode host so we can communicate with dockers on the princeton-daq computer. @jesusvasquez333 claimed that it worked immediately with the devboard but I'm having trouble connecting to the shelf manager without `network_mode: host`. In particular, I'm getting this error when I try to connect from within the docker: 
```
cryo@4c88db4943e3:/usr/local/src/smurf-streamer$ ipmitool -I lan -H shm-smrf-sp01
Password:
Address lookup for shm-smrf-sp01 failed
Could not open socket!
```
Am I missing anything in my setup? Do I have to use a different interface?

**Comment by jesusvasquez333** [comment]
The issue is that in host mode, the shelfmanager’s IP address can no be resolved. We can try to use the shelfmanager IP address instead of its node name. 

Alternative, you can pass the AMC carrier IP address directly, instead of shelfmanager and slot number. This is the way the dev board works (as there is not shelfmanager in that case)

These are just workarounds. I will need to do some testing to find the best way to solve this.

**Comment by jesusvasquez333** [comment]
@jlashner OK, here is a complete example on how to run smurf containers without using the network host mode. 

This is a complete example, on how to run multiple servers (2 in this example), and a single client (pysmurf) talking to all of them. Also, this example allows the servers to use either the PCIe interface or Ethernet. This example however, must run the servers without an attach GUI. 

I'm using these files for this example:

**.env:**
```bash
$ cat .env
user_uid=1000:1001
user_name=cryo
shm_ip=134.79.217.72
```

**docker-compose.yml:**
```yml
$ cat docker-compose.yml
version: '3.4'

# Default configuration for all apps
x-app: &default-app
  user: ${user_uid}
  environment:
  - location=${PWD}
  - EPICS_CA_ADDR_LIST=172.28.0.255 # Broadcast address
  - EPICS_CA_AUTO_ADDR_LIST=NO
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  extra_hosts:
    - "shm-smrf-sp01:${shm_ip}"
  volumes:
  - /data:/data
  - /home/${user_name}/.bash_history:/home/${user_name}/.bash_history
  - /home/${user_name}/.ipython:/home/${user_name}/.ipython
  security_opt:
  - "apparmor=docker-smurf"
  tty: true
  stdin_open: true

# Default configuration for all server apps
x-server: &default-server
  <<: *default-app
  image: tidair/pysmurf-server:v1.0.0
  devices:
  - /dev/datadev_0
  - /dev/datadev_1
  networks:
  - a-fpga
  - epics-ca
  logging:
    options:
      tag: smurf_server


services:
  # Server for carrier in slot 2
  smurf_server_s2:
    <<: *default-server
    container_name: smurf_server_s2
    ports:
    - target: 9004
      published: 9004
      protocol: tcp
    - target: 9005
      published: 9005
      protocol: tcp
    command: -w smurf_server_s2 -S shm-smrf-sp01 -N 2 -e smurf_server_s2 -c pcie

  # Server for carrier in slot 5
  smurf_server_s5:
    <<: *default-server
    container_name: smurf_server_s5
    ports:
    - target: 9010
      published: 9010
      protocol: tcp
    - target: 9011
      published: 9011
      protocol: tcp
    command: -w smurf_server_s5 -S shm-smrf-sp01 -N 5 -e smurf_server_s5 -c pcie

  # Client
  pysmurf:
    <<: *default-app
    image: tidair/pysmurf-client:v4.0.0
    container_name: pysmurf
    networks:
    - epics-ca
    command: --config-file  '/usr/local/src/pysmurf/cfg_files/stanford/experiment_fp30_cc02-03_lbOnlyBay0.cfg'
    logging:
      options:
        tag: pysmurf
    depends_on:
    - smurf_server_s2
    - smurf_server_s5

networks:
  # This network will be used for the communication with the FPGAs
  # This network is of type 'bridge'
  a-fpga:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000

  # This network will be used for the communication between servers and client using EPICS Channel Access
  # This network is of type 'bridge'
  epics-ca:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.28.0.0/24"
      # The broadcast address for this subnet is 172.28.0.255
```

Some descriptions:
- As we are not running in network host mode, inside the docker container, we won't be able to talk to the ATCA shelfmanager using its node name `shm-smrf-sp01` (which is defined in the host server's `/etc/hosts`). So, we would need to use its IP address instead. In this example, however, to make it a little more flexible, I'm defining a variable `shm_ip` in the `.env` file with this IP address, and then I'm adding the host name `shm-smrf-sp01` with this IP address to the container in the `docker-compose.yml` file, under the section `extra_hosts`.
- As we I'm running multiple servers in this example, int the EPICS client we must set the EPICS setting environmental variable `EPICS_CA_ADDR_LIST` to the broadcast address of the network where the servers are. So, in this example I created a custom network called `epics-ca` and I assigned a known subnet address (in order to know its broadcast address). Then I attach all server and client container to this network, and I set the `EPICS_CA_ADDR_LIST` to the broadcast address of this network (`172.28.0.255`) under the `environment` section.
- In order to be able to talk to the FPGA via Ethernet (instead of using the PCIe interface) from the servers, I defined a second network call `a-fpga` for this purpose. This communications requires the use of jumbo frames, so I set the `mtu` of this network to 9000. After some testing I discovered that when a container is attached to multiple bridge networks, the first one created is the one use to access external hosts (in this case the FPGA is an external host, as it is attached to the host's external network); and the networks seems to be created alphabetically. So, I added an `a-` to the beginning of this network name so that it is created first. (I haven't find this in the official documentation yet).
- We are running the servers without a GUI attached to them. However, it is still possible to attached a remote GUI using the ZMQ interface. For this to work however, we need to expose the ZMQ ports the servers use to the host. I do this under the `ports` sections. (Note: each server application uses 2 TCP ports for this ZMQ interface, and the port number are `9000 + slot_number*2`, and `9000 + slot_number*2 + 1` )

Using this docker compose file, one can then start the 2 server and the client doing:
```bash
$ docker-compose up -d

$ docker-compose ps
     Name                    Command               State                       Ports
---------------------------------------------------------------------------------------------------------
pysmurf           start_client.sh --epics sm ...   Up
smurf_server_s2   start_server.sh -w smurf_s ...   Up      0.0.0.0:9004->9004/tcp, 0.0.0.0:9005->9005/tcp
smurf_server_s5   start_server.sh -w smurf_s ...   Up      0.0.0.0:9010->9010/tcp, 0.0.0.0:9011->9011/tcp
```

Once the servers are running, it is possible to access both from the `pysmurf` client, for example:
```bash dock
$ docker container attach pysmurf
In [1]: import epics

In [2]: epics.caget('smurf_server_s2:AMCc:SmurfApplication:StartupArguments', as_string=True)
Out[2]: '-w smurf_server_s2 -e smurf_server_s2 -l 0 -a 10.0.1.102 -z /tmp/fw/rogue_MicrowaveMuxBpEthGen2_v0.0.5.zip -d /tmp/fw/smurf_cfg/defaults/defaults_c03_lb_lb.yml --enable-em22xx'

In [3]: epics.caget('smurf_server_s5:AMCc:SmurfApplication:StartupArguments', as_string=True)
Out[3]: '-w smurf_server_s5 -e smurf_server_s5 -l 3 -a 10.0.1.105 -z /tmp/fw/rogue_MicrowaveMuxBpEthGen2_v0.0.5.zip -d /tmp/fw/smurf_cfg/defaults/defaults_c03_lb_lb.yml --enable-em22xx'

In [4]:
```

It is also possible to attach a remote GUI to these servers. For example to attach a GUI to the server running on slot 2:
```bash
$ docker run -ti --rm \
--log-opt tag=guis \
-u $(id -u cryo):$(id -g cryo) \
--net host \
-e DISPLAY \
-e location=${PWD} \
--mount type=bind,src=/home/cryo/.Xauthority,dst=/home/cryo/.Xauthority,ro \
--entrypoint connect_remote_gui.py \
tidair/smurf-rogue:R2.7.0 \
--slot 2
```

In this example, I was using the PCIe interface. However, Ethernet can be use instead. You just need to change the option `-c pcie` to `-c eth` in the `command` section of each server.

---

Finally, here it is a simplify example. To simply run 1 server and 1 client, only supporting the PCIe interface, I can use these files instead:

**.env:**
```bash
$ cat .env
user_uid=1000:1001
user_name=cryo
shm_ip=134.79.217.72
```

**docker-compose.yml:**
```yml
$ cat docker-compose.yml
version: '3.4'

# Default configuration for apps
x-app: &default-app
  user: ${user_uid}
  environment:
  - location=${PWD}
  - EPICS_CA_AUTO_ADDR_LIST=YES
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  extra_hosts:
    - "shm-smrf-sp01:${shm_ip}"
  volumes:
  - /data:/data
  - /home/${user_name}/.bash_history:/home/${user_name}/.bash_history
  - /home/${user_name}/.ipython:/home/${user_name}/.ipython
  security_opt:
  - "apparmor=docker-smurf"
  tty: true
  stdin_open: true

services:
  smurf_server_s5:
    <<: *default-app
    image: tidair/pysmurf-server:v1.0.0
    container_name: smurf_server_s5
    devices:
    - /dev/datadev_0
    - /dev/datadev_1
    ports:
    - target: 9010
      published: 9010
      protocol: tcp
    - target: 9011
      published: 9011
      protocol: tcp
    command: -w smurf_server_s5 -S shm-smrf-sp01 -N 5 -e smurf_server_s5 -c pcie
    logging:
      options:
        tag: smurf_server

  pysmurf_s5:
    <<: *default-app
    image: tidair/pysmurf-client:v4.0.0
    container_name: pysmurf_s5
    command: --epics smurf_server_s5 --config-file  '/usr/local/src/pysmurf/cfg_files/stanford/experiment_fp30_cc02-03_lbOnlyBay0.cfg'
    logging:
      options:
        tag: pysmurf
    depends_on:
    - smurf_server_s5
```

Start the container with 
```bash
$ docker-compose up -d

$ docker-compose ps
     Name                    Command               State                       Ports
---------------------------------------------------------------------------------------------------------
pysmurf_s5        start_client.sh --epics sm ...   Up
smurf_server_s5   start_server.sh -w smurf_s ...   Up      0.0.0.0:9010->9010/tcp, 0.0.0.0:9011->9011/tcp
```

And then you can start using the client, for example:
```bash
$ docker container attach pysmurf_s5
In [1]: import epics

In [2]: epics.caget(epics_prefix+':AMCc:SmurfApplication:StartupArguments', as_string=True)
Out[2]: '-w smurf_server_s5 -e smurf_server_s5 -l 3 -a 10.0.1.105 -z /tmp/fw/rogue_MicrowaveMuxBpEthGen2_v0.0.5.zip -d /tmp/fw/smurf_cfg/defaults/defaults_c03_lb_lb.yml --enable-em22xx'

In [3]: S = pysmurf.client.SmurfControl(epics_root=epics_prefix,cfg_file=config_file,setup=True,make_logfile=False,shelf_manager="shm-smrf-sp01")
(...snip...)

In [4]: S.get_frame_count()
Out[4]: 70652

In [5]:
```
