### ISSUE TITLE
Tab complete no longer working at UCSD

### ISSUE THREAD

**Issue by jseibert575** [slaclab/pysmurf#324]
Tab complete in the ipython terminal on smurf-srv14 at UCSD no longer seems to be working, either in VNC or from a different terminal session. Are there any ways to diagnose the problem and fix it? Thanks!

**Comment by jlashner** [comment]
I'm pretty sure this has to do with the switch to not mounting the entire home directory. It looks like the way the pysmurf docker is started now, since the home directory inside the docker container isn't mounted `/home/cryo` is owned by root, and therefore the cryo user inside the docker container can't write to it. I'm not sure this is what's causing the tab-complete problem, but its possible...

**Comment by swh76** [comment]
@jseibert575 can you please paste steps for reproducing the problem?  Are you trying to tab complete a path or a command or...?

**Comment by jseibert575** [comment]
@swh76, in the ipython terminal opened from shawnhammer, just trying to tab-complete pysmurf commands, like S.get_amplifier_biases(), nothing happens. Seems true for all pysmurf functions, though other things (like stored variables) tab-complete fine.

**Comment by swh76** [comment]
This looks like a problem on our end.  Made this JIRA ticket https://jira.slac.stanford.edu/browse/ESCRYODET-630 (only SLAC folks will be able to access that link).

**Comment by jesusvasquez333** [comment]
I see the same behavior in our server at SLAC:
- tab-complete works when doing this for example: `import num<TAB>`
- tab-complete does not work when doing this for example `a = np.<TAB>`
- These both however work on a normal `python3` shell, instead of a `ipython3` shell.

I think @jlashner is right, this is happening now that we are not mounting the whole `/home/cryo` directory inside the container. We are however mounting `/home/cryo/.ipython/` directory. 

Need to investigate what is missing...

**Comment by jesusvasquez333** [comment]
I did a quick test and @jlashner is correct. The directory `/home/cryo` inside the container is owned by `root`, so the `cryo` user can not write to it; and that seems to be needed for the ipython tab complete feature.

**Comment by jesusvasquez333** [comment]
The issue comes from the base docker image used to create the pysmurf docker image, here: https://github.com/slaclab/smurf-base-docker/blob/master/Dockerfile#L64

That command creates the `cryo` user, but it doesn't create its home directory.

**Comment by jesusvasquez333** [comment]
@jseibert575 if this is a critical issue for you, a quick **workaround** until we release a new version with a fix, will be to do this:
- First, create a new directory in the host server which will be mounted as as the cryo's home directory inside the pysmurf docker container. For example:
```bash
cryo@smurf-srv14:~$ mkdir -p /data/home_dockers
```

- Then modify either the `docker-compose.yml`, or `run.sh` file used to start the pysmurf docker container, and mount this new directory as the cryo's home:
  - If you are using a `run.sh` script then  add this new line `-v /data/home_dockers:/home/${user}`. The resulting script should look like this:
```bash
#!/usr/bin/env bash

user="cryo"

docker run -it --rm  \
  --log-opt tag=pysmurf \
  --security-opt apparmor=docker-smurf \
  -u $(id -u ${user}):$(id -g ${user}) \
  --net host \
  -e DISPLAY \
  -e location=${PWD} \
  -e EPICS_CA_ADDR_LIST=127.255.255.255 \
  -e EPICS_CA_MAX_ARRAY_BYTES=80000000 \
  -v /data/home_dockers:/home/${user} \
  -v /home/${user}/.Xauthority:/home/${user}/.Xauthority \
  -v /home/${user}/.bash_history:/home/${user}/.bash_history \
  -v /home/${user}/.ipython:/home/${user}/.ipython \
  -v /data:/data \
  -v ${PWD}/pysmurf:/usr/local/src/pysmurf \
  --entrypoint bash \
  --workdir /usr/local/src/pysmurf \
  tidair/pysmurf-client:v4.0.0-rc21
```
  - If you are using a `docker-compose.yml` file, then add this line `-  /data/home_dockers:/home/${user_name}` under the `x-pysmurf.volumes` section. The resulting `x-pysmurf` section should look like this:
```
x-pysmurf:
  &pysmurf
  <<: *default-gui-app
  image: tidair/pysmurf-client:v4.0.0-rc21
  container_name: pysmurf_s${slot}
  volumes:
  - /data:/data
  - /data/home_dockers:/home/${user_name}
  - /home/${user_name}/.Xauthority:/home/${user_name}/.Xauthority
  - /home/${user_name}/.bash_history:/home/${user_name}/.bash_history
  - /home/${user_name}/.ipython:/home/${user_name}/.ipython
  - ${PWD}/pysmurf:/usr/local/src/pysmurf
  #command: --epics smurf_server_s${slot}
  entrypoint: bash
  logging:
    options:
      tag: pysmurf
  depends_on:
  - smurf_server_s${slot}
```

This won't be needed in the next release.
